import { normalizePastedText } from "./paste";

const BASE = "https://youtube-transcript.ai/transcript";

/** youtube-transcript.ai 응답에서 본문만 추출 */
export function cleanYoutubeTranscriptAi(raw: string): string {
  let t = raw.trim();
  if (!t) return "";

  t = t.replace(
    /\n*Generated by https:\/\/youtube-transcript\.ai[\s\S]*$/i,
    ""
  );

  const body = t.match(/##\s*Transcript\s*\n([\s\S]*)/i);
  if (body?.[1]) t = body[1];

  t = t
    .replace(/^#+\s.*$/gm, "")
    .replace(/^Source video:.*$/gim, "")
    .replace(/^Language:.*$/gim, "")
    .replace(/^Other available languages:.*$/gim, "")
    .replace(/^To request a specific language:.*$/gim, "")
    .replace(/^Interactive version.*$/gim, "")
    .replace(/\[(\d{1,2}:\d{2}(?::\d{2})?)\]/g, " ")
    .replace(/^\d{1,2}:\d{2}(?::\d{2})?\s+/gm, "")
    .replace(/[♪♫]+/g, " ")
    .replace(/\n{3,}/g, "\n\n")
    .replace(/[ \t]{2,}/g, " ");

  t = dedupeTranscriptRepeats(t);
  return normalizePastedText(t);
}

/** youtube-transcript.ai: 세그먼트 겹침으로 같은 구절이 2~3회 연속 반복되는 경우 제거 */
export function dedupeTranscriptRepeats(text: string): string {
  const words = text.split(/\s+/).filter(Boolean);
  if (words.length < 6) return text.trim();

  const out: string[] = [];
  let i = 0;
  while (i < words.length) {
    let matched = false;
    const maxLen = Math.min(18, Math.floor((words.length - i) / 2));
    for (let size = maxLen; size >= 3; size--) {
      const chunk = words.slice(i, i + size);
      const chunkKey = chunk.join(" ");
      let end = i + size;
      while (end + size <= words.length) {
        const nextKey = words.slice(end, end + size).join(" ");
        if (nextKey !== chunkKey) break;
        end += size;
      }
      if (end > i + size) {
        out.push(...chunk);
        i = end;
        matched = true;
        break;
      }
    }
    if (!matched) {
      out.push(words[i]);
      i++;
    }
  }
  return out.join(" ").replace(/\s+/g, " ").trim();
}

function looksLikeFailure(text: string, status: number): boolean {
  if (status >= 400) return true;
  const lower = text.toLowerCase();
  if (text.length < 40) return true;
  if (/no transcript|not found|error|unavailable|captions? (were )?not/i.test(lower)) {
    return true;
  }
  if (/<!doctype html>|<html[\s>]/i.test(text)) return true;
  return false;
}

/** 서버에서 youtube-transcript.ai 자막을 가져온다 (키 불필요) */
export async function fetchYoutubeTranscriptAi(
  videoId: string,
  opts?: { lang?: string; timeoutMs?: number }
): Promise<{ text: string; langTried: string; sourceUrl: string }> {
  const id = videoId.trim();
  if (!/^[a-zA-Z0-9_-]{11}$/.test(id)) {
    throw new Error("유효한 YouTube 영상 ID가 아닙니다.");
  }

  const timeoutMs = opts?.timeoutMs ?? 45_000;
  const preferred = opts?.lang?.trim();
  // 기본(원어) 먼저 → 한국어 → 영어 (한국어 영상이 ?lang=ko 404인 경우 대비)
  const attempts = [
    "",
    ...(preferred ? [preferred] : []),
    "ko",
    "en",
  ].filter((v, i, arr) => arr.indexOf(v) === i);

  let lastError = "자막을 가져오지 못했습니다.";

  for (const lang of attempts) {
    const sourceUrl = lang
      ? `${BASE}/${id}.txt?lang=${encodeURIComponent(lang)}`
      : `${BASE}/${id}.txt`;

    try {
      const res = await fetch(sourceUrl, {
        method: "GET",
        headers: {
          Accept: "text/plain, text/markdown, */*",
          "User-Agent":
            "Mozilla/5.0 (compatible; YouTubeFactCheck/1.0; +local)",
        },
        signal: AbortSignal.timeout(timeoutMs),
        cache: "no-store",
      });

      const raw = await res.text();
      if (looksLikeFailure(raw, res.status)) {
        lastError = `자막 응답이 비어 있거나 오류입니다. (${lang || "default"}, HTTP ${res.status})`;
        continue;
      }

      const text = cleanYoutubeTranscriptAi(raw);
      if (text.length < 80) {
        lastError = "가져온 자막이 너무 짧습니다.";
        continue;
      }

      return {
        text,
        langTried: lang || "default",
        sourceUrl,
      };
    } catch (e) {
      lastError =
        e instanceof Error ? e.message : "자막 API 요청에 실패했습니다.";
    }
  }

  throw new Error(
    `${lastError} youtube-transcript.ai에서 자막이 없는 영상이거나 일시 오류일 수 있습니다.`
  );
}
