import assert from "node:assert/strict";
import { cleanYoutubeTranscriptAi } from "../src/lib/youtube-transcript-ai";

const sample = `# Transcript: 테스트 영상

Source video: https://www.youtube.com/watch?v=AAAAAAAAAAA
Language: ko · Duration: 1:00 · Words: 20
Other available languages: a-ko (ko) [auto]
To request a specific language: https://youtube-transcript.ai/transcript/AAAAAAAAAAA.txt?lang=LANG_CODE

## Transcript

[0:01] 안녕하세요. 오늘은 인류 진화에 대해 이야기합니다.
[0:20] 루시와 아르디는 서로 다른 종이었습니다.

Generated by https://youtube-transcript.ai — free YouTube transcript & summary extractor.
Interactive version (with AI chat & translation): https://youtube-transcript.ai/?v=AAAAAAAAAAA
`;

const cleaned = cleanYoutubeTranscriptAi(sample);
assert.ok(cleaned.includes("인류 진화"));
assert.ok(cleaned.includes("루시"));
assert.ok(!cleaned.includes("Generated by"));
assert.ok(!cleaned.includes("Source video"));
assert.ok(cleaned.length > 80);
console.log("OK cleanYoutubeTranscriptAi", cleaned.length, "chars");
console.log(cleaned.slice(0, 160));
